ipfs/go-unixfs

.gx/lastpubver
package.json

Depends on:
- https://github.com/libp2p/go-libp2p-kad-dht/pull/186
- https://github.com/ipfs/go-ipld-git/pull/22
- https://github.com/ipfs/go-ipfs-chunker/pull/2
- https://github.com/ipfs/go-ipfs-exchange-offline/pull/4
- https://github.com/libp2p/go-libp2p-routing-helpers/pull/4
- https://github.com/libp2p/go-libp2p-pubsub-router/pull/5
- https://github.com/ipfs/go-path/pull/4
This PR with gx updates has been created using gx-workspace: https://github.com/ipfs/gx-workspace

gx: update go-cid

---

hamt/hamt.go
importer/trickle/trickledag.go
io/resolve.go
mod/dagmodifier.go
test/utils.go
unixfs.go
unixfs_test.go

Fixes: https://github.com/ipfs/go-ipfs/issues/5217, https://github.com/ipfs/go-unixfs/issues/17

fix(fsnode): issue #17

---

hamt/hamt.go
hamt/hamt_test.go

Speed up LS operation on sharded directories [#4908](https://github.com/ipfs/go-ipfs/issues/4908)
Test the use of [EnumerateChildrenAsync](https://github.com/ipfs/go-merkledag/blob/master/merkledag.go#L351) as a fast way of fetching an arbitrary MerkleDAG w/o concern for order (https://github.com/ipfs/go-ipfs/issues/5487)
In the `EnumLinks` method for HAMT, instead of calling ForEachLink (synchronous), use `EnumerateChildrenAsync` 
`EnumerateChildrenAsync` requires a root CID, a `GetLinks` function which returns a list of child IPLD Links to traverse for a given CID, and a `visit` function which returns a boolean of whether to traverse a given CID. In our case, `visit` is a function that just returns true (always visit), and filtering nodes to visit is instead handled by filtering the …

Use EnumerateChildrenAsync in for enumerating HAMT links

---

hamt/hamt.go

fixes https://github.com/ipfs/go-unixfs/issues/28

refactor(hamt): remove child interface from hamt package

---

hamt/hamt.go
hamt/hamt_test.go
io/directory.go
io/directory_test.go
unixfs.go

child of https://github.com/ipfs/go-ipfs/issues/5600
Implement an EnumLinksAsync method on Directory interface to support streaming version of `ls` command
- Add LinkResult type to unix-fs - is an ipld Link or an error
- Add EnumLinksAsync method to Directory interface, returns channel of directory links or error
- Add EnumLinksAsync method to Shard interface in HAMT, returns channel
of directory links or error
- EnumLinks method in Shard interface in HAMT uses EnumLinksAsync now
- modify makeAsyncTrieGetLinks to use channel
- Arguably an async link enumeration is sufficiently generic it could live in go-ipld-format, and LinkResult is a type that is not super specific to go-unixfs
- However I would prefer to hold on putting LinkResult in go-ipld-format to a later commit where we a …

feat(Directory): Add EnumLinksAsync method

---

importer/helpers/helpers.go

When try to write the patch for https://github.com/ipfs/go-ipfs/issues/5135. I found that the comments in [importer/helpers/helpers.go](https://github.com/ipfs/go-unixfs/blob/master/importer/helpers/helpers.go) is not correct.  Reference https://github.com/ipfs/go-ipfs/issues/5135#issuecomment-423797051.

Fix comments relative to DefaultLinksPerBlock

---

.gx/lastpubver
importer/balanced/balanced_test.go
importer/helpers/dagbuilder.go
importer/importer.go
importer/trickle/trickle_test.go
mod/dagmodifier.go
package.json
test/utils.go

See https://github.com/ipfs/go-ipfs/pull/5925

Unixfs: enforce refs on files when using nocopy

---

importer/helpers/dagbuilder.go

We now just use the AbsPath field for both URLs and file paths.

chore: remove URL field

---

go.mod
go.sum
hamt/hamt.go

@Stebalien 
Update to the last go-merkledag, with the functional opts. 
Note: i'm not entirely sure the root has to be visited here.

update the the last go-merkledag

---

go.mod
unixfs.go
unixfs_test.go

The file size of a symlink is the symlink data.

fix: correctly handle symlink file sizes

---

io/dagreader.go
io/dagreader_test.go

We had a hack that "pretended" seeking worked when it didn't as go's HTTP
library uses seeks to determine the file size. However,
1. I'm changing the gateway to actually rely on seeking working as specified.
2. We don't even need this hack. The gateway performs two types of seeks (unless
a range query is passed):
1. It seeks to the beginning. We can always shortcut this.
2. It seeks to the end. The gateway now has a special "lazy" seeker to avoid
seeking until we actually try to _read_. Therefore, we don't need a hack
for that either.

fix(dagreader): remove a buggy workaround for a gateway issue

---

hamt/hamt.go
hamt/hamt_test.go

If we try deleting a bunch of files _before_ reading them, we'll panic because they haven't been loaded. This works around that by using the _link_ directly when the child hasn't been loaded.
fixes https://github.com/ipfs/go-ipfs/issues/6860

fix: fix a panic when deleting

---

io/dagreader.go
unixfs.go

While looking at https://github.com/ipfs/go-ipfs/issues/7916 I noticed the file size returned by https://github.com/ipfs/go-ipfs/blob/master/core/commands/get.go#L80 is 0 for this raw dag. 
```
◉ ipfs get QmasYd9docsEaozsdZxCp29yfoZoUJDrvqgkT8Hry66N24
Saving file(s) to QmasYd9docsEaozsdZxCp29yfoZoUJDrvqgkT8Hry66N24
111.50 KiB / 111.50 KiB [===========================================================================] 100.00% 0s
```
```
◉ curl localhost:8082/ipfs/QmasYd9docsEaozsdZxCp29yfoZoUJDrvqgkT8Hry66N24 -o /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  111k  100  111k    0     0  13.6M      0 --:--:-- --:--:-- --:--:-- 13.6M
```

correct file size for raw node

---

io/directory.go
io/directory_test.go

Toward https://github.com/ipfs/go-mfs/issues/86.
To avoid breaking compatibility we change as little as possible here but probably both `HAMTDirectory` and `BasicDirectory` should be made private. (In that case we would export `SwitchToSharding` from `BasicDirectory` to the `UpgradeableDirectory`.)

feat: add UpgradeableDirectory

---

io/directory.go

Normally this is called from the constructor with the size cleared but I added the same call to the unlikely case we underflow because of a bug. Maybe that call shouldn't exist in the first place but wasn't sure how to handle that without leaving the computation unbalanced. In any case, this is not an addition like the other functions but a computation from scratch so this is the right fix.

fix(directory): initialize size when computing it

---

io/directory.go

Extracted from review in https://github.com/ipfs/go-unixfs/pull/94#discussion_r679369036.
This ended up being a much cleaner patch than I originally anticipated. Since `go-merkledag` provides an API to add both nodes and links we now add links directly to the node through `AddRawLink` while maintaining the current `AddChild` API (not needing to expand it with a public variant and keeping the plumbing `addLinkChild` function private) that now converts itself the node to a link (a conversion that would otherwise happen inside the replaced `AddNodeLink` call).

Optimization 1 for `switchToBasic` function in unsharding PR

---

hamt/hamt.go
io/directory.go

When automatically switching a BasicDirectory to a HAMTDirectory because it
grew too big, the current code:
* loops every link in the BasicDirectory
* reads each node referenced by those links
* adds the nodes to a new HAMTDirectory shard, which in turn:
* writes the nodes to the DAG service (they were just read from there!)
* makes a link out of them (identical to the link in the BasicDirectory!)
This would happen to about (~4000 nodes), which are fully read and written for nothing.
This PR adds a new SetLink method to the HAMT Shard which, instead of taking
an ipld.Node like Set(), takes directly an ipld.Link. Then it updates
switchToSharding() to pass the links in the BasicDirectory directy, rather
than reading all the nodes.
Note that switchToBasic() works like this already, only …

Make switchToSharding more efficient

---

hamt/hamt.go
hamt/hamt_test.go

Context: https://github.com/ipfs/kubo/issues/9063
When stressing `go-mfs` over fuzz testing, we can cause nil pointer exceptions like:
```
testing.go:1349: panic: runtime error: invalid memory address or nil pointer dereference
goroutine 6908 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x90
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1349 +0x1f2
panic({0xa6ec60, 0xefe2e0})
/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/ipfs/go-unixfs/hamt.(*childer).has(...)
/home/ajnavarro/go/pkg/mod/github.com/ipfs/go-unixfs@v0.4.0/hamt/hamt.go:886
github.com/ipfs/go-unixfs/hamt.(*Shard).swapValue(0xc0029067e0, {0xbc1440, 0xc000024088}, 0xc0000e5348, {0xc00014e001, 0xf10}, 0xc002462420) …
```

Fix: panic when childer is nil

---

hamt/hamt_test.go

Fixes CI, no need to release this.

test: fix tests after hamt issues fixes

---

file/unixfile.go
go.mod
go.sum
importer/helpers/dagbuilder.go
version.json

A release is needed to keep usefull changes since go-libipfs was added in the go-car PR.
```
647ce18c (tag: v0.4.4, origin/master, origin/HEAD, master) chore: release v0.4.4
b7f6de07 fix: correctly handle return errors
98e2622d fix: correctly handle errors in balancedbuilder's Layout
6727e33d test: fix tests after hamt issues fixes
467d139a (tag: v0.4.3) Merge pull request from GHSA-q264-w97q-q778
1e875f46 (security/fix/hamt-width-issues) chore: release v0.4.3
dbcc43ec fix: correctly handle degenerate hamts while reading data
6609090f sync: update CI config files (#137)
323bb63c (tag: v0.4.2) chore: version 0.4.2 (#136)
```

remove go-libipfs dependency
